### ISSUE TITLE
support comma three

### ISSUE THREAD

**Issue by sshane** [sshane/openpilot-installer-generator#6]
haven't tried it yet

**Comment by nelsonjchen** [comment]
theoretically doesn't work now, obviously.

**Comment by nelsonjchen** [comment]
Rough thoughts:

- [ ] Build a new AGNOST installer with the same idea that the modified NEOS openpilot installer was using such as painting and stretching compiled strings to be replaced at runtime by the PHP script.
- [ ] Handle new User Agent of AGNOS installer and instead use AGNOS OP installer as template.

I can't test or develop this but that would be what I would do.

**Comment by lskov** [comment]
And you are so right, just tried it on my comma three and doesn’t work. :) 
I can test it, not sure how to make the AGNOST installer. Instead a did a clone through SSH to get my latest changes.
